-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-06-14 15:10:07 ICT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE company (
    companyid        INTEGER NOT NULL,
    address          VARCHAR2(70) NOT NULL,
    city             VARCHAR2(30) NOT NULL,
    province         VARCHAR2(35) NOT NULL,
    companyname      VARCHAR2(40) NOT NULL,
    numberofemployee INTEGER,
    profilephoto     VARCHAR2(50)
);

CREATE UNIQUE INDEX company__idx ON
    company (
        companyid
    ASC );

CREATE UNIQUE INDEX company__idxv1 ON
    company (
        companyid
    ASC );

ALTER TABLE company ADD CONSTRAINT company_pk PRIMARY KEY ( companyid );

ALTER TABLE company ADD CONSTRAINT company_companyid_un UNIQUE ( companyid );

CREATE TABLE photo_project (
    photos            VARCHAR2(70),
    project_projectid INTEGER NOT NULL
);

CREATE TABLE progress_photos (
    photos                 VARCHAR2(70),
    talent_talentid        INTEGER NOT NULL,
    ppgr_project_projectid INTEGER NOT NULL
);

CREATE TABLE project (
    projectid           INTEGER NOT NULL,
    company_companyid   INTEGER NOT NULL,
    projectname         VARCHAR2(50) NOT NULL,
    requiredjobposition VARCHAR2(30) NOT NULL,
    talentrequirement   VARCHAR2(50) NOT NULL,
    projectdescription  VARCHAR2(300),
    projectlocation     VARCHAR2(40) NOT NULL,
    project_startdate   DATE NOT NULL,
    project_enddate     DATE,
    project_photos      VARCHAR2(100),
    deadline            DATE NOT NULL,
    salary_min          NUMBER NOT NULL,
    salary_max          NUMBER,
    status              VARCHAR2(30) NOT NULL,
    talentneededmin     NUMBER,
    talentneededmax     NUMBER
);

ALTER TABLE project ADD CONSTRAINT project_pk PRIMARY KEY ( projectid );

CREATE TABLE project_application (
    project_projectid INTEGER NOT NULL,
    talent_talentid   INTEGER NOT NULL
);

CREATE INDEX project_application__idx_prj ON
    project_application (
        project_projectid
    ASC );

CREATE INDEX project_application__idx_tln ON
    project_application (
        talent_talentid
    ASC );

ALTER TABLE project_application ADD CONSTRAINT project_application_pk PRIMARY KEY ( project_projectid,
                                                                                    talent_talentid );

CREATE TABLE project_progress (
    description       VARCHAR2(35) NOT NULL,
    "Date"            DATE NOT NULL,
    deadline          DATE NOT NULL,
    project_projectid INTEGER NOT NULL
);

ALTER TABLE project_progress ADD CONSTRAINT project_progress_pk PRIMARY KEY ( project_projectid );

CREATE TABLE talent (
    talentid              INTEGER NOT NULL,
    birthdate             DATE NOT NULL,
    gender                VARCHAR2(15) NOT NULL,
    cv                    VARCHAR2(50),
    portofolio            VARCHAR2(50),
    certificate           VARCHAR2(50),
    status                VARCHAR2(15) NOT NULL,
    expectationworktype   VARCHAR2(40) NOT NULL,
    availableworkhoursmin DATE,
    availableworkhoursmax DATE,
    skills                VARCHAR2(70) NOT NULL,
    preferences           VARCHAR2(50),
    link_ig               VARCHAR2(60),
    link_fb               VARCHAR2(60),
    link_linkedin         VARCHAR2(60),
    link_twitter          VARCHAR2(60),
    profilephoto          VARCHAR2(50)
);

ALTER TABLE talent ADD CONSTRAINT talent_user_userid_un PRIMARY KEY ( talentid );

ALTER TABLE talent ADD CONSTRAINT tln_pk UNIQUE ( talentid );

CREATE TABLE "User" (
    userid    INTEGER NOT NULL,
    usertype  VARCHAR2(25) NOT NULL,
    firstname VARCHAR2(30) NOT NULL,
    lastname  VARCHAR2(30),
    email     VARCHAR2(50) NOT NULL,
    password  VARCHAR2(25) NOT NULL,
    phonenum  VARCHAR2(15)
);

ALTER TABLE "User" ADD CONSTRAINT user_pk PRIMARY KEY ( userid );

CREATE TABLE work_experience (
    talent_talentid INTEGER NOT NULL,
    jobposition     VARCHAR2(40) NOT NULL,
    companyname     VARCHAR2(40) NOT NULL,
    jobtype         VARCHAR2(40) NOT NULL,
    worktime        DATE NOT NULL
);

ALTER TABLE work_experience ADD CONSTRAINT work_experience_pk PRIMARY KEY ( talent_talentid );

ALTER TABLE company
    ADD CONSTRAINT company_user_fk FOREIGN KEY ( companyid )
        REFERENCES "User" ( userid );

ALTER TABLE photo_project
    ADD CONSTRAINT pht_prj_fk FOREIGN KEY ( project_projectid )
        REFERENCES project ( projectid );

ALTER TABLE progress_photos
    ADD CONSTRAINT prg_pht_prj_prg_fk FOREIGN KEY ( ppgr_project_projectid )
        REFERENCES project_progress ( project_projectid );

ALTER TABLE progress_photos
    ADD CONSTRAINT progress_photos_talent_fk FOREIGN KEY ( talent_talentid )
        REFERENCES talent ( talentid );

ALTER TABLE project_application
    ADD CONSTRAINT project_application_project_fk FOREIGN KEY ( project_projectid )
        REFERENCES project ( projectid );

ALTER TABLE project_application
    ADD CONSTRAINT project_application_talent_fk FOREIGN KEY ( talent_talentid )
        REFERENCES talent ( talentid );

ALTER TABLE project
    ADD CONSTRAINT project_company_fk FOREIGN KEY ( company_companyid )
        REFERENCES company ( companyid );

ALTER TABLE project_progress
    ADD CONSTRAINT project_progress_project_fk FOREIGN KEY ( project_projectid )
        REFERENCES project ( projectid );

ALTER TABLE talent
    ADD CONSTRAINT talent_user_fk FOREIGN KEY ( talentid )
        REFERENCES "User" ( userid );

ALTER TABLE work_experience
    ADD CONSTRAINT work_experience_talent_fk FOREIGN KEY ( talent_talentid )
        REFERENCES talent ( talentid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             4
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
